version: "3"

services:
  strapi:
    container_name: "strapi-cms"
    build:
      context: ./app
      dockerfile: Dockerfile.dev
    restart: unless-stopped
    env_file: .env
    volumes:
      - pxcookie-config:/opt/app/config
      - pxcookie-src:/opt/app/src
      - pxcookie-package-json:/opt/package.json
      - pxcookie-yarn-lock:/opt/yarn.lock
      - pxcookie-uploads:/opt/app/public/uploads
    ports:
      - 1337:1337
    networks:
      - strapi
    depends_on:
      - db

  db:
    image: postgres
    container_name: "strapi-db"
    env_file: .env
    ports:
      - 5555:5432
    volumes:
      - pxcookie-db:/var/lib/postgresql/data
    networks:
      - strapi

volumes:
  pxcookie-db:
  pxcookie-config:
  pxcookie-src:
  pxcookie-package-json:
    driver_opts:
      type: none
      device: /root/mycms/app/package.json
      o: bind
  pxcookie-yarn-lock:
    driver_opts:
      type: none
      device: /root/mycms/app/yarn.lock
      o: bind
  pxcookie-uploads:

networks:
  strapi:
    name: strapi-network
    driver: bridge
