version: "3"

services:
  strapi:
    container_name: "strapi-cms"
    build:
      context: ./app
      dockerfile: Dockerfile.dev
    restart: unless-stopped
    env_file: .env
    ports:
      - 1337:1337
    networks:
      - strapi
    depends_on:
      - db

  db:
    image: postgres
    container_name: "strapi-db"
    env_file: .env
    ports:
      - 5555:5432
    networks:
      - strapi

networks:
  strapi:
    name: strapi-network
    driver: bridge
